openapi: "3.0.0"
info:
  version: 1.0.0
  title: Games-Explorer

tags:
  - name: Games
    description: ""

paths:
  /games/{gameName}/servers:
    x-vertx-event-bus:
      address: edge.games.registries
      timeout: 5000
    get:
      operationId: getAll
      tags:
        - Games
      parameters:
        - name: gameName
          in: path
          schema:
            type: string
          required: true
          description: "Game Identifier"
      responses:
        200:
          description: "Get Servers list"